[package]
name = "test-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
jsonwebtoken = { version = "10.2.0", features =["default", "aws_lc_rs"]}
p384 = "0.13.1"
pem = "3.0.6"
x509-parser = "0.18"

